language: shell

env:
  global:
    RUNNER="./qt_installer.sh"

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then npm install -g jshint ; fi

install:
  - ${RUNNER}

script:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then jshint control_script.js ; fi
  - qmake --version

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      env:
        - QT_INSTALLER_DOWNLOAD_NAME="qt-unified-mac-x64-online.dmg"
        - QT_INSTALLER_VARS="${TRAVIS_BUILD_DIR}/ci/vars_mac.js"
        - PATH="/opt/Qt/5.12.3/clang_64/bin:${PATH}"

    # 64-bit Windows
    - os: windows
      env:
        # Yes, x86 in installer name is correct.
        - QT_INSTALLER_DOWNLOAD_NAME="qt-unified-windows-x86-online.exe"
        - QT_INSTALLER_VARS="${TRAVIS_BUILD_DIR}/ci/vars_win_x64.js"
        - PATH="/c/Qt/5.12.3/msvc2017_64/bin:${PATH}"

    # 32-bit Windows
    - os: windows
      env:
        - QT_INSTALLER_DOWNLOAD_NAME="qt-unified-windows-x86-online.exe"
        - QT_INSTALLER_VARS="${TRAVIS_BUILD_DIR}/ci/vars_win_x86.js"
        - PATH="/c/Qt/5.12.3/msvc2017/bin:${PATH}"
